name: todo_list
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # database storage
  sqflite: ^2.0.0+3

  # format DateTime
  intl: ^0.17.0

  # display todos in grid
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  path: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/todo_ico.png"

  flutter_lints: ^2.0.0


flutter:
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: fonts/NotoSansJP-Medium.otf

  assets:
    - assets/
  uses-material-design: true